
const example = require("../imgs/example.jpeg");

export const mockData = [
  {
    user: 1,
    id: 1,
    name: "Test1",
    plant_species: "asd",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae quos exercitationem modi, accusamus quas qui iure debitis nemo aliquid quaerat iste aliquam quisquam hic numquam praesentium laudantium fugiat voluptatibus est!",
    date_added: "2022-06-02",
    how_often: 3,
    last_watered: 1,
    img: example,
    tracked: true,
  },
  {
    user: 1,
    id: 2,
    name: "Test2",
    plant_species: "asd",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae quos exercitationem modi, accusamus quas qui iure debitis nemo aliquid quaerat iste aliquam quisquam hic numquam praesentium laudantium fugiat voluptatibus est!",
    date_added: "2022-06-02",
    how_often: 3,
    last_watered: 1,
    img: example,
    tracked: true,
  },
  {
    user: 1,
    id: 3,
    name: "Test3",
    plant_species: "asd",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae quos exercitationem modi, accusamus quas qui iure debitis nemo aliquid quaerat iste aliquam quisquam hic numquam praesentium laudantium fugiat voluptatibus est!",
    date_added: "2022-06-02",
    how_often: 3,
    last_watered: 1,
    img: example,
    tracked: true,
  },
  {
    user: 1,
    id: 4,
    name: "Test4",
    plant_species: "asd",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae quos exercitationem modi, accusamus quas qui iure debitis nemo aliquid quaerat iste aliquam quisquam hic numquam praesentium laudantium fugiat voluptatibus est!",
    date_added: "2022-06-02",
    how_often: 3,
    last_watered: 1,
    img: example,
    tracked: true,
  },
  {
    user: 1,
    id: 5,
    name: "Test5",
    plant_species: "asd",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae quos exercitationem modi, accusamus quas qui iure debitis nemo aliquid quaerat iste aliquam quisquam hic numquam praesentium laudantium fugiat voluptatibus est!",
    date_added: "2022-06-02",
    how_often: 3,
    last_watered: 1,
    img: example,
    tracked: true,
  },
  {
    user: 1,
    id: 6,
    name: "Test6",
    plant_species: "asd",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae quos exercitationem modi, accusamus quas qui iure debitis nemo aliquid quaerat iste aliquam quisquam hic numquam praesentium laudantium fugiat voluptatibus est!",
    date_added: "2022-06-02",
    how_often: 3,
    last_watered: 1,
    img: example,
    tracked: true,
  },
  {
    user: 1,
    id: 7,
    name: "Test7",
    plant_species: "asd",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae quos exercitationem modi, accusamus quas qui iure debitis nemo aliquid quaerat iste aliquam quisquam hic numquam praesentium laudantium fugiat voluptatibus est!",
    date_added: "2022-06-02",
    how_often: 3,
    last_watered: 1,
    img: example,
    tracked: true,
  },
  {
    user: 1,
    id: 8,
    name: "Test8",
    plant_species: "asd",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae quos exercitationem modi, accusamus quas qui iure debitis nemo aliquid quaerat iste aliquam quisquam hic numquam praesentium laudantium fugiat voluptatibus est!",
    date_added: "2022-06-02",
    how_often: 3,
    last_watered: 1,
    img: example,
    tracked: true,
  },
  {
    user: 1,
    id: 9,
    name: "Test9",
    plant_species: "asd",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae quos exercitationem modi, accusamus quas qui iure debitis nemo aliquid quaerat iste aliquam quisquam hic numquam praesentium laudantium fugiat voluptatibus est!",
    date_added: "2022-06-02",
    how_often: 3,
    last_watered: 1,
    img: example,
    tracked: true,
  },
];