# Generated by Django 4.0.4 on 2022-06-16 13:18

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_plant_tracked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_path),
        ),
    ]
