version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src:/var/app/src
      # - ./dist:/var/app/dist
      - ./tsconfig.json:/var/app/tsconfig.json
      - ./tsconfig.build.json:/var/app/tsconfig.build.json

  postgres:
    image: postgres:14.2
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: hucuplant

